CREATE TABLE groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  color VARCHAR(20) NOT NULL
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  email VARCHAR(255),
  password_reset_required BOOLEAN NOT NULL DEFAULT FALSE,
  password_reset_issued_at TIMESTAMP
);

CREATE TABLE mail_settings (
  id BIGINT PRIMARY KEY,
  username VARCHAR(255),
  app_password VARCHAR(255),
  from_address VARCHAR(255),
  updated_at TIMESTAMP
);

CREATE TABLE todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author VARCHAR(255) NOT NULL,
  assignee VARCHAR(255),
  title VARCHAR(255) NOT NULL,
  detail TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
  priority VARCHAR(10) NOT NULL DEFAULT 'MEDIUM',
  start_date DATE,
  due_date DATE,
  group_id BIGINT,
  user_id BIGINT NOT NULL,
  CONSTRAINT fk_todos_group FOREIGN KEY (group_id) REFERENCES groups(id),
  CONSTRAINT fk_todos_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE todo_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  todo_id BIGINT NOT NULL,
  action VARCHAR(20) NOT NULL,
  detail VARCHAR(500),
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_todo_history_todo FOREIGN KEY (todo_id) REFERENCES todos(id) ON DELETE CASCADE
);

CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(30) NOT NULL,
  entity_type VARCHAR(50) NOT NULL,
  entity_id BIGINT,
  user_id BIGINT,
  old_value CLOB,
  new_value CLOB,
  ip_address VARCHAR(64),
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE todo_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  todo_id BIGINT NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  stored_filename VARCHAR(64) NOT NULL,
  content_type VARCHAR(100),
  size BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_todo_attachments_todo FOREIGN KEY (todo_id) REFERENCES todos(id) ON DELETE CASCADE
);

